name: Hello World Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # or the branch you are working on

# A workflow run is made up of one or more jobs
jobs:
  say-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step uses the 'echo' command to output "Hello World!"
      - name: Say Hello
        run: echo "Hello World!"

  date-now:
    runs-on: ubuntu-latest
    steps:
      - name: Print the time
        run: ls -l
